---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insights
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: insights
        env:
        - name: RELATED_IMAGE_INSIGHTS_PROXY
          value: "registry.redhat.io/3scale-amp2/apicast-gateway-rhel8:3scale2.15"
        - name: INSIGHTS_BACKEND_DOMAIN
          value: "console.redhat.com"
        - name: USER_AGENT_PREFIX
<<<<<<< HEAD
          value: "cryostat-operator/4.0.0-dev"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: INSIGHTS_ENABLED
          value: "true"
        - name: INSIGHTS_URL
          value: "http://insights-proxy.$(OPERATOR_NAMESPACE).svc.cluster.local:8080"
=======
          value: "cryostat-operator/4.1.0-dev"
>>>>>>> ecfc6f3 (fix(insights): correct environment variable order in overlay (#1073))
