# Permissions for Cryostat to validate tokens and perform
# actions with the web-ui
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: oauth-client
rules:
- apiGroups:
  - operator.cryostat.io
  resources:
  - cryostats
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - services
  - secrets
  verbs:
  - create
  - get
  - delete
# - apiGroups:
#   - ""
#   resources:
#   - replicationcontrollers
#   - endpoints
#   verbs:
#   - get
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   verbs:
#   - create
#   - get
# - apiGroups:
#   - apps
#   resources:
#   - daemonsets
#   - replicasets
#   - statefulsets
#   verbs:
#   - get
