# Add descriptors for target namespace elements
- op: add
  path: /spec/customresourcedefinitions/owned/0/specDescriptors/-
  value:
    description: "A namespace whose workloads Cryostat should be able to connect and record"
    displayName: "Target Namespace"
    path: targetNamespaces[0]
    x-descriptors:
    - "urn:alm:descriptor:io.kubernetes:Namespace"
- op: add
  path: /spec/customresourcedefinitions/owned/0/statusDescriptors/-
  value:
    description: "A namespace whose workloads Cryostat should be able to connect and record"
    displayName: "Target Namespace"
    path: targetNamespaces[0]
    x-descriptors:
    - "urn:alm:descriptor:io.kubernetes:Namespace"
